language: node_js
node_js:
- '7'
before_install:
- npm install -g npm@'>=5.5.1'
install:
- npm install
- npm ls || true
- npm install coveralls
script:
- git reset --hard
- npm run build
- npm run test
after_success:
- npm run es6:coveralls
deploy:
  provider: npm
  skip_cleanup: true
  email: neapp-ci@me.dgardiner.net
  api_key:
    secure: bTfQxOr95TP9W9iB9PzX0tUeXQ8B29wSiUxtfg0jwpRLrr2BQcrqkDmft0l8O1Qk7mXi88GGZSzz2Z1QNdp4Yir4+Idt88ltMqd87TWgAGIBWnc0jB0ZiDmBTnoeIEKP5AdKBPh8vKMsKx12FDzij1Q769d398835/Vk17/3Kf7VCRrctoBh4SUhn9ucz5stZ+0RCmInnADDxdiQo6ke+5vfXb8DoDDDCZNWRRRrgk5uRv2mUa8Kkc2SjMQSW5F0L8HcNf+izJ5sFfHzE/s6iQr4x+1OTi8zBMRB4CUBxqmje5PtzuAE+h6nx4J3dymhFwqmWQazeH5azdCxkKZbIv+KZYoBAfcpu4AikLxxKeln2XaLBx3cSbSC6PMTVltONLwGfSFNYrWTRDlzvdl0IQhphIhtS30pizv3lWNzAh4m9DotWgwp+AzaFTYwRE1i+12Vc+z8p8EAtUOzQ3MCUvk8mXGC5zMtXgSuFIsrz8A/9/Eu2egSMHLQTWbMKOHqNyySuq9vQFJrZc/ysFv6c8qaAjECnhamm+P1+u65EUjs+Ls+GR7WaU725eWv/XAJH7D5LDGZj/2jtVu2HcmueYpuyu8OL6PC6eG3hX7Ogm/ep247uZVsgcKDobxcvsYtr5fOkIHKai7EO9YsJvYLuZgcpZjysmul2GbRksvtol8=
  on:
    repo: fuzeman/wes
    tags: true
